### ISSUE TITLE
Better documentation for "lib" versus "main"

### ISSUE THREAD

**Issue by elemoine** [openlayers/closure-util#34]
Reading the doc I find it hard to understand the difference between the manager options "lib" and "main". So it would make sense to me to provide more details in the documentation, and when one or the other should be used.

**Comment by elemoine** [comment]
I know better understand the difference between `lib` and `main` in the manager, but I find it very very difficult to explain and document. I tried to document it tonight, but I failed.

**Comment by tschaub** [comment]
There is some unnecessary complexity here due to the fact that I tried to make the `closure-util` server a drop-in replacement for our use of Plovr in ol3.  We could likely simplify things (and potentially make `closure-util` more useful) if we changed the way our examples work and the test server is launched.  I know this is not enough to act on now, but I just wanted to provide a little context for the existing weirdness.
